# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

FROM jupyter/pyspark-notebook:8015c88c4b11
RUN conda install -y nose && \
    conda install -y -n python2 nose

# Setup a sphinx environment for doc building
COPY docs/environment.yml /tmp
RUN conda env create -f /tmp/environment.yml

# Add to the python2 environment for testing
RUN bash -c 'source activate python2 && \
    conda install -y requests nose'