channels:
  - conda-forge
  - defaults
dependencies:
  - docker-py>=3.5.0
  - future
  - jinja2>=2.10
  - jupyter_client>=6.1
  - jupyter_core>=4.6.0
  - jupyter_server>=1.2
  - paramiko>=2.1.2
  - pexpect>=4.2.0
  - pip
  - pycryptodomex>=3.9.7
  - python-kubernetes>=4.0.0
  - pyzmq>=17.0.0
  - requests>=2.7,<3.0
  - tornado>=6.1
  - traitlets>=4.2.0
  - watchdog
  - yarn-api-client>=1.0

  # Test Requirements
  - ipykernel
  - mock
  - pytest
  - pytest-tornasync
  - websocket-client

  # Code Style
  - flake8

  # Documentation Requirements
  - sphinx_rtd_theme
  - sphinx>=3
  - recommonmark
  - sphinx-markdown-tables

  - pip:
    - jupyter_server>=1.2
