channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter_core>=4.4.0
  - jupyter_client>=5.2.0
  - notebook>=5.3.0,<6.0
  - jupyter_kernel_gateway>=2.1.0
  - traitlets>=4.2.0
  - tornado>=4.2.0,<6.0
  - requests>=2.7,<3.0
  - paramiko>=2.1.2
  - yarn-api-client>=0.3.0
  - pexpect>=4.2.0
  - pycrypto>=2.6.1
  - pyzmq>=17.0.0
  - python-kubernetes>=4.0.0
  - docker-py>=3.5.0
  - pip

  # Documentation Requirements
  - sphinx_rtd_theme
  - sphinx=1.8.3
  - recommonmark
  # Test Requirements
  - nose
  - mock
  - websocket-client
  - pytest
