channels:
  - conda-forge
  - defaults
dependencies:
  - docker-py>=3.5.0
  - future
  - jinja2>=3.1
  - jupyter_client>=6.1,<7 # Remove cap once EG supports kernel provisioners
  - jupyter_core>=4.7.0
  - jupyter_server>=1.7,<2 # Remove cap (increase floor) once EG suport kernel provisioners
  - paramiko>=2.1.2
  - pexpect>=4.2.0
  - pip
  - pre-commit
  - pycryptodomex>=3.9.7
  - python-kubernetes>=18.20.0
  - pyzmq>=20.0.0,<25 # Pyzmq 25 removes deprecated code that jupyter_client 6 uses, remove if v6 gets updated
  - requests>=2.14.2
  - tornado>=6.1
  - traitlets>=5.3.0
  - watchdog>=2.1.3
  - yarn-api-client>=1.0

  # Test Requirements
  - coverage
  - ipykernel
  - mock
  - pytest<8.1.0
  - pytest-tornasync
  - websocket-client

  # Code Style
  - flake8

  - pip:
      - .
      - -r docs/doc-requirements.txt
