channels:
  - conda-forge
  - defaults
dependencies:
  - docker-py>=3.5.0
  - jinja2>=2.10
  - jupyter_client>=5.2.0
  - jupyter_core>=4.4.0
  - notebook>=5.7.6,<7.0
  - paramiko>=2.1.2
  - pexpect>=4.2.0
  - pip
  - pycrypto>=2.6.1
  - python-kubernetes>=4.0.0
  - pyzmq>=17.0.0
  - requests>=2.7,<3.0
  - tornado>=4.2.0
  - traitlets>=4.2.0
  - yarn-api-client>=0.3.6,<0.4.0

  # Test Requirements
  - nose
  - mock
  - websocket-client
  - pytest

  # Code Style
  - flake8

  # Documentation Requirements
  - sphinx_rtd_theme
  - sphinx=1.8.3
  - recommonmark
  #- sphinx-markdown-tables
