channels:
  - conda-forge
  - defaults
dependencies:
  - docker-py>=3.5.0
  - future
  - jinja2>=3.1
  - jupyter_client>=6.1
  - jupyter_core>=4.6.0
  - jupyter_server>=1.7
  - paramiko>=2.1.2
  - pexpect>=4.2.0
  - pip
  - pre-commit
  - pycryptodomex>=3.9.7
  - python-kubernetes>=18.20.0
  - pyzmq>=20.0.0
  - requests>=2.7,<3.0
  - tornado>=6.1
  - traitlets>=4.2.0
  - watchdog
  - yarn-api-client>=1.0

  # Test Requirements
  - ipykernel
  - mock
  - pytest
  - pytest-tornasync
  - websocket-client

  # Code Style
  - flake8

  - pip:
      - .
      - -r docs/doc-requirements.txt
