version: "3.5"

# A docker user network is created and referenced by the service.  This network
# must also get conveyed to launched kernel containers and that occurs via the env variable: EG_DOCKER_NETWORK

# Notes (FIXMEs):
# 1. We need to address the need to run as UID 0 (root).  This appears to be required inorder to create containers/services from within.
# 2. Using endpoint-mode dnsrr (which appears to be required inorder for kernel container to send the connection info response back)
# also required mode=host on any published ports. :-(
# 3. We only use one replica since session affinity is another point of investigation in Swarm
services:

  enterprise-gateway:
    image: elyra/enterprise-gateway:dev
    user: root
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      # It's often helpful to mount the kernelspec files from the host into the container.
      # Since this could be a deployed to a swarm cluster, it is recommended in this case that these be mounted on an
      # NFS volume available to all nodes of the cluster, or a volume plugin is used instead of a bind mount.
      # - /usr/local/share/jupyter/kernels:/usr/local/share/jupyter/kernels
    environment:
      - "EG_DOCKER_NETWORK=${EG_DOCKER_NETWORK:-enterprise-gateway_enterprise-gateway}"
      - "EG_KERNEL_LAUNCH_TIMEOUT=${EG_KERNEL_LAUNCH_TIMEOUT:-60}"
      - "EG_CULL_IDLE_TIMEOUT=${EG_CULL_IDLE_TIMEOUT:-3600}"
      - "EG_KERNEL_WHITELIST=${EG_KERNEL_WHITELIST:-['r_docker','python_docker','python_tf_docker','python_tf_gpu_docker','scala_docker']}"
      - "EG_MIRROR_WORKING_DIRS=${EG_MIRROR_WORKING_DIRS:-False}"
      - "KG_PORT=${KG_PORT:-8888}"
    networks:
      - enterprise-gateway
    ports:
      - target: ${KG_PORT:-8888}
        published: ${KG_PORT:-8888}
        protocol: tcp
        mode: host
    labels:
      app: "enterprise-gateway"
      component: "enterprise-gateway"
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
      labels:
        app: "enterprise-gateway"
        component: "enterprise-gateway"

networks:
  enterprise-gateway:
