apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: enterprise-gateway-allow-all
  namespace: enterprise-gateway
spec:
  podSelector: {}
  ingress:
    - {}
  egress:
    - {}
  policyTypes:
    - Ingress
    - Egress