{{- if and  (.Values.deployment.serviceAccountName) (.Values.global.rbac) }}
---
apiVersion: v1
kind: ServiceAccount
{{- if .Values.global.imagePullSecrets }}
imagePullSecrets:
  {{- $parent := . -}}
  {{- range .Values.global.imagePullSecrets }}
  - name: {{ . }}
  {{- end }}
{{- end }}
metadata:
  name: {{ .Values.deployment.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: enterprise-gateway
    component: enterprise-gateway
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- range $key, $val := .Values.global.commonLabels }}
    {{ $key }}: "{{ $val }}"
  {{- end }}
{{- if .Values.deployment.annotations }}
  annotations:
  {{- range $key, $val := .Values.deployment.annotations }}
    {{ $key }}: "{{ $val }}"
  {{- end }}
{{- end }}
{{- end }}
