{{- if and (.Values.imagePullSecretsCreate.enabled) (.Values.imagePullSecretsCreate.secrets) -}}
---
{{- $root := .Values }}
{{- range .Values.imagePullSecretsCreate.secrets }}
apiVersion: v1
data:
  .dockerconfigjson: {{ .data }}
kind: Secret
metadata:
  name: {{ .name }}
{{- if ($root.imagePullSecretsCreate.annotations) -}}
  {{- with $root.imagePullSecretsCreate.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

type: kubernetes.io/dockerconfigjson
{{- end }}
---
{{- end }}
