{{- define "kernel-role" }}
{{- if .Values.externalCluster.autoConfigureRemote }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  # Referenced by EG_KERNEL_CLUSTER_ROLE in the Deployment
  name: kernel-controller
  labels:
    app: enterprise-gateway
    component: kernel
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list", "create", "delete"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["list", "create"]
  - apiGroups: [""]
    resources: ["services", "persistentvolumeclaims"]
    verbs: ["list"]
{{- end }}
{{- end }}
