{{- if and  (.Values.kip.serviceAccountName) (.Values.global.rbac) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kip-controller
  labels:
    app: enterprise-gateway
    component: kernel-image-puller
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- range $key, $val := .Values.global.commonLabels }}
    {{ $key }}: "{{ $val }}"
  {{- end }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list", "create", "delete"]
  {{- if .Values.kip.podSecurityPolicy.create }}
  - apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    resourceNames:
      - "kip-psp"
    verbs:
      - use
  {{- end }}
{{- end }}
