# Site settings
title: Jupyter Enterprise Gateway
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/enterprise_gateway" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
