name: enterprise_gateway_docs
channels:
  - conda-forge
  - defaults
  - free
dependencies:
  - pip
  - python=3.7
  - pip:
    - recommonmark
    - sphinx_rtd_theme
    - sphinx>=3
    - sphinx-markdown-tables
